### ISSUE TITLE
combine the upload & download feature into one website

### ISSUE THREAD

**Issue by kartikey-codes** [kartikey-codes/FTPdemo#3]

**Comment by abhishek-kumar-91** [comment]
I want to work on this issue, can you assign me?

**Comment by kartikey-codes** [comment]
@abhishek-kumar-91  please add your changes inside the combined  website folder

**Comment by abhishek-kumar-91** [comment]
@kartikey-codes  there is no show hacktoberfest tag on this issue, can you generate

**Comment by abhishek-kumar-91** [comment]
“HACKTOBERFEST-ACCEPTED” LABEL,

**Comment by kartikey-codes** [comment]
@abhishek-kumar-91 added

**Comment by abhishek-kumar-91** [comment]
thank you

**Comment by sdroyc** [comment]
Hi! Could you assign me this!
