### ISSUE TITLE
enhance css for ftpupload

### ISSUE THREAD

**Issue by kartikey-codes** [kartikey-codes/FTPdemo#7]

**Comment by IVAVI17** [comment]
I would like to make my contribution under this topic, kindly assign this to me 

thanks

**Comment by anshulkumarx7** [comment]
CAN U PLEASE ASSIGN ME THIS??

**Comment by kartikey-codes** [comment]
@anshulkumarx7 all the best , don't forget to follow me and give this repo a star!
